Базовая стилизация страниц
htmlacademy-htmlcss/812205-sedona-32 pull request #5
Opened 2021-11-04 10:29 UTC by farkhad

2021-11-06 09:31 UTC, mouxez requested changes

2021-11-06 09:31 UTC, mouxez commented on css/styles.css
> +  background-color: #FFF;
Не рекомендуется использовать сокращения. Важно в одном стиле писать всё. или так #ff11dd или так #FF11DD

2021-11-06 09:31 UTC, mouxez commented on css/styles.css
> +  font-family: "PT Sans", sans-serif;
Вот тут почитай как это делается
https://htmlacademy.ru/blog/boost/tutorial/fonts-loading

2021-11-06 11:47 UTC, farkhad commented on css/styles.css
> +  font-family: "PT Sans", sans-serif;
Не могу понять, что я упустил :) 
У меня не указан local("PT Sans"), Вы это имеете в виду?

2021-11-07 16:22 UTC, mouxez approved these changes

2021-11-07 16:23 UTC, merged